Repository CSC207-2023Y-UofT/course-project-DoorKeepers, pull requests merged in 2023-08, with the labels that each got.

#12 [Feature 4] Monthly Menu Completed
  src/main/java/use_cases/monthly_menu/MonthMenuOB.java
  src/main/java/use_cases/monthly_menu/MonthMenuOD.java
  src/main/java/use_cases/monthly_menu/UpdateViewIB.java
  src/main/java/use_cases/monthly_menu/UpdateViewID.java
  src/main/java/use_cases/monthly_menu/UpdateViewUCI.java
  src/main/java/views/monthly_menu/MonthMenuP.java
  src/main/java/views/monthly_menu/MonthMenuV.java
  src/main/java/views/monthly_menu/UpdateViewC.java
  src/test/java/use_cases/monthly_menu/UpdateViewUCITest.java
Labels: enhancement

#11 1 feature 1 load a session
  src/main/java/Main.java
  src/main/java/entities/Category.java
  src/main/java/entities/Expense.java
  src/main/java/entities/MonthlyStorage.java
  src/main/java/entities/SessionStorage.java
  src/main/java/use_cases/session_load/SessionLoadException.java
  src/main/java/use_cases/session_load/SessionLoadIB.java
  src/main/java/use_cases/session_load/SessionLoadID.java
  src/main/java/use_cases/session_load/SessionLoadOB.java
  src/main/java/use_cases/session_load/SessionLoadOD.java
  src/main/java/use_cases/session_load/SessionLoadUCI.java
  src/main/java/use_cases/session_load/SessionStorageG.java
  src/main/java/views/file_session_storage/FileSessionStorage.java
  src/main/java/views/main_menu/MainMenuV.java
  src/main/java/views/session_load/SessionLoadC.java
  src/main/java/views/session_load/SessionLoadMainMenuVB.java
  src/main/java/views/session_load/SessionLoadMenuV.java
  src/main/java/views/session_load/SessionLoadMenuVB.java
  src/main/java/views/session_load/SessionLoadP.java
  src/test/java/entities/SessionStorageTest.java
  src/test/java/use_cases/session_load/SessionLoadUCITest.java
  src/test/java/views/file_session_storage/FileSessionStorageTest.java
Labels: enhancement

#17 Corrected casts in MonthlyMenuV constructor so that they don't throw a ClassCastException
  src/main/java/views/monthly_menu/MonthMenuV.java
Labels: bug

#14 [Feature 8] Improve Entity Documentation and Testing
  src/main/java/entities/Category.java
  src/main/java/entities/EntityException.java
  src/main/java/entities/Expense.java
  src/main/java/entities/MonthlyStorage.java
  src/main/java/entities/SessionStorage.java
  src/test/java/entities/CategoryTest.java
  src/test/java/entities/ExpenseTest.java
  src/test/java/entities/MonthlyStorageTest.java
  src/test/java/entities/SessionStorageTest.java
Labels: documentation, enhancement

#19 Switch EXIT_ON_CLOSE to HIDE_ON_CLOSE
  src/main/java/views/monthly_menu/MonthMenuV.java
Labels: invalid

#15 [Feature 7] Generate Graphical Summary
  build.gradle
  src/main/java/use_cases/generate_summary_use_case/GenerateSummaryIB.java
  src/main/java/use_cases/generate_summary_use_case/GenerateSummaryID.java
  src/main/java/use_cases/generate_summary_use_case/GenerateSummaryOB.java
  src/main/java/use_cases/generate_summary_use_case/GenerateSummaryOD.java
  src/main/java/use_cases/generate_summary_use_case/GenerateSummaryUCI.java
  src/main/java/use_cases/generate_summary_use_case/GenerateSummaryUCInterpreter.java
  src/main/java/views/generate_summary_views/GenerateSummaryC.java
  src/main/java/views/generate_summary_views/GenerateSummaryP.java
  src/main/java/views/generate_summary_views/GenerateSummaryV.java
  src/test/java/use_cases/generate_summary_use_case/GenerateSummaryUCInterpreterTest.java
Labels: enhancement

#21 [Feature 3] Create a New Month Completed
  src/main/java/use_cases/create_new_month/NewMonthIB.java
  src/main/java/use_cases/create_new_month/NewMonthID.java
  src/main/java/use_cases/create_new_month/NewMonthOB.java
  src/main/java/use_cases/create_new_month/NewMonthOD.java
  src/main/java/use_cases/create_new_month/NewMonthUCI.java
  src/main/java/use_cases/monthly_menu/MonthMenuOB.java
  src/main/java/use_cases/monthly_menu/MonthMenuOD.java
  src/main/java/use_cases/monthly_menu/UpdateViewIB.java
  src/main/java/use_cases/monthly_menu/UpdateViewUCI.java
  src/main/java/views/create_new_month/NewMonthC.java
  src/main/java/views/create_new_month/NewMonthP.java
  src/main/java/views/create_new_month/NewMonthV.java
  src/main/java/views/load_monthly_menu/LoadMonthMenuVB.java
  src/main/java/views/monthly_menu/MonthMenuV.java
  src/test/java/use_cases/create_new_month/NewMonthUCITest.java
  src/test/java/use_cases/monthly_menu/UpdateViewUCITest.java
Labels: enhancement

#20 [Feature 2] Main Menu
  src/main/java/Main.java
  src/main/java/use_cases/main_menu/SessionSaveIB.java
  src/main/java/use_cases/main_menu/SessionSaveID.java
  src/main/java/use_cases/main_menu/SessionSaveOB.java
  src/main/java/use_cases/main_menu/SessionSaveOD.java
  src/main/java/use_cases/main_menu/SessionSaveUCI.java
  src/main/java/views/main_menu/MainMenuC.java
  src/main/java/views/main_menu/MainMenuP.java
  src/main/java/views/main_menu/MainMenuV.java
  src/main/java/views/session_load/SessionLoadMainMenuVB.java
  src/test/java/use_cases/main_menu/SessionSaveUCITest.java
  src/test/java/views/file_session_storage/FileSessionStorageTest.java
Labels: enhancement

#26 [Feature 9] openMonthMenu and openMainMenu
  src/main/java/use_cases/monthly_menu/UpdateViewUCI.java
  src/main/java/views/create_new_month/NewMonthV.java
  src/main/java/views/generate_summary_views/GenerateSummaryV.java
  src/main/java/views/monthly_menu/MonthMenuV.java
Labels: enhancement

#13 [Feature 5] Add/Edit Category
  .gitignore
  .idea/.gitignore
  src/main/java/use_cases/add_edit_category_use_case/CategoryIB.java
  src/main/java/use_cases/add_edit_category_use_case/CategoryID.java
  src/main/java/use_cases/add_edit_category_use_case/CategoryOB.java
  src/main/java/use_cases/add_edit_category_use_case/CategoryOD.java
  src/main/java/use_cases/add_edit_category_use_case/CategoryUCI.java
  src/main/java/views/add_edit_category_views/AddCategoryV.java
  src/main/java/views/add_edit_category_views/CategoryC.java
  src/main/java/views/add_edit_category_views/CategoryP.java
  src/main/java/views/add_edit_category_views/EditCategoryV.java
  src/test/java/use_cases/add_edit_category_use_case/CategoryUCITest.java
Labels: enhancement

#23 [Feature 6] Add/Edit Expenses
  src/main/java/use_cases/add_edit_expenses_use_case/ExpenseIB.java
  src/main/java/use_cases/add_edit_expenses_use_case/ExpenseID.java
  src/main/java/use_cases/add_edit_expenses_use_case/ExpenseOB.java
  src/main/java/use_cases/add_edit_expenses_use_case/ExpenseOD.java
  src/main/java/use_cases/add_edit_expenses_use_case/ExpenseUCI.java
  src/main/java/views/add_edit_epense_views/AddExpenseV.java
  src/main/java/views/add_edit_epense_views/EditExpenseV.java
  src/main/java/views/add_edit_epense_views/ExpenseC.java
  src/main/java/views/add_edit_epense_views/ExpenseP.java
  src/test/java/use_cases/add_edit_expenses_use_case/ExpenseUCITest.java
Labels: enhancement

#28 Connected MainMenuV to MonthMenuV and NewMonthV with their new implementations
  src/main/java/views/main_menu/MainMenuV.java
Labels: enhancement

#31 [Feature 12] Additional Tests for GenerateSummary
  src/test/java/use_cases/generate_summary_use_case/GenerateSummaryUCITest.java
  src/test/java/use_cases/generate_summary_use_case/GenerateSummaryUCInterpreterTest.java
Labels: enhancement

#30 [Feature 9] Month Menu Button Reactions
  src/main/java/views/add_edit_category_views/AddCategoryV.java
  src/main/java/views/add_edit_category_views/EditCategoryV.java
  src/main/java/views/add_edit_epense_views/AddExpenseV.java
  src/main/java/views/add_edit_epense_views/EditExpenseV.java
  src/main/java/views/monthly_menu/MonthMenuV.java
Labels: enhancement

#36 [Feature 15] Implement LoadMonthMenuVB in MainMenuV
  src/main/java/views/main_menu/MainMenuV.java
Labels: enhancement

#25 [Feature 10] Create a README.md
  README.md
Labels: documentation

#44 Show monthly budget on MonthMenuV.
  src/main/java/use_cases/monthly_menu/MonthMenuOD.java
  src/main/java/use_cases/monthly_menu/UpdateViewUCI.java
  src/main/java/views/monthly_menu/MonthMenuV.java
  src/test/java/use_cases/monthly_menu/UpdateViewUCITest.java
Labels: enhancement

#40 Fix Pothole Case in Entities
  src/main/java/entities/Category.java
  src/main/java/entities/Expense.java
  src/main/java/entities/MonthlyStorage.java
  src/main/java/entities/SessionStorage.java
Labels: documentation

#54 Improve SOLID in NewMonthUCI
  src/main/java/entities/SessionStorage.java
  src/main/java/use_cases/create_new_month/NewMonthUCI.java
  src/test/java/entities/SessionStorageTest.java
  src/test/java/use_cases/create_new_month/NewMonthUCITest.java
  src/test/java/use_cases/main_menu/SessionSaveUCITest.java
  src/test/java/use_cases/monthly_menu/UpdateViewUCITest.java
  src/test/java/use_cases/session_load/SessionLoadUCITest.java
  src/test/java/views/file_session_storage/FileSessionStorageTest.java
Labels: enhancement

#56 Implementation of Factory Design Pattern in Entities
  src/main/java/entities/Category.java
  src/main/java/entities/CategoryCreatorInputData.java
  src/main/java/entities/CategoryEditorInputData.java
  src/main/java/entities/CategoryFactory.java
  src/main/java/entities/Expense.java
  src/main/java/entities/ExpenseCreatorInputData.java
  src/main/java/entities/ExpenseEditorInputData.java
  src/main/java/entities/ExpenseFactory.java
  src/main/java/entities/MonthObject.java
  src/main/java/entities/MonthObjectFactory.java
  src/main/java/entities/MonthObjectFactoryInputData.java
  src/test/java/entities/CategoryFactoryTest.java
  src/test/java/entities/ExpenseFactoryTest.java
Labels: enhancement

#60 46 implementation of factory design pattern in Add/Edit features
  src/main/java/entities/CategoryCreatorInputData.java
  src/main/java/entities/CategoryEditorInputData.java
  src/main/java/entities/ExpenseCreatorInputData.java
  src/main/java/entities/ExpenseEditorInputData.java
  src/main/java/entities/MonthObjectFactory.java
  src/main/java/entities/MonthObjectFactoryInputData.java
  src/main/java/use_cases/add_edit_category_use_case/CategoryUCI.java
  src/main/java/use_cases/add_edit_expenses_use_case/ExpenseUCI.java
  src/main/java/views/add_edit_category_views/AddCategoryV.java
  src/main/java/views/add_edit_category_views/EditCategoryV.java
  src/main/java/views/add_edit_epense_views/AddExpenseV.java
  src/main/java/views/add_edit_epense_views/EditExpenseV.java
Labels: enhancement

#59 Address intellij warnings
  project_plan_dev.md
  src/main/java/entities/MonthObject.java
  src/main/java/entities/MonthObjectFactoryInputData.java
  src/main/java/use_cases/add_edit_category_use_case/CategoryID.java
  src/main/java/use_cases/add_edit_category_use_case/CategoryUCI.java
  src/main/java/use_cases/add_edit_expenses_use_case/ExpenseID.java
  src/main/java/use_cases/add_edit_expenses_use_case/ExpenseOD.java
  src/main/java/use_cases/add_edit_expenses_use_case/ExpenseUCI.java
  src/main/java/use_cases/create_new_month/NewMonthUCI.java
  src/main/java/use_cases/monthly_menu/MonthMenuOD.java
  src/main/java/use_cases/session_load/SessionLoadIB.java
  src/main/java/use_cases/session_load/SessionLoadOB.java
  src/main/java/views/add_edit_category_views/AddCategoryV.java
  src/main/java/views/add_edit_category_views/EditCategoryV.java
  src/main/java/views/add_edit_epense_views/AddExpenseV.java
  src/main/java/views/add_edit_epense_views/EditExpenseV.java
  src/main/java/views/create_new_month/NewMonthV.java
  src/main/java/views/main_menu/MainMenuV.java
  src/main/java/views/session_load/SessionLoadC.java
  src/main/java/views/session_load/SessionLoadMenuV.java
  src/main/java/views/session_load/SessionLoadMenuVB.java
  src/test/java/use_cases/main_menu/SessionSaveUCITest.java
  src/test/java/use_cases/session_load/SessionLoadUCITest.java
  src/test/java/views/file_session_storage/FileSessionStorageTest.java
Labels: enhancement

#61 Improve README documentation
  README.md
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  images/add_category.png
  images/add_expense.png
  images/closed_issue.png
  images/closed_project.png
  images/create_branch.png
  images/create_pr.png
  images/create_project.png
  images/edit_category.png
  images/edit_expense.png
  images/graphical_summary.png
  images/link_branch.png
  images/link_project.png
  images/main_menu.png
  images/month_menu.png
  images/new_issue.png
  images/new_pr.png
  images/rename.png
  images/session_load.png
  images/set_tags.png
  images/test_coverage.png
  project_plan_dev.md
Labels: documentation
